### ISSUE TITLE
Extraneous 'default' and 'adhoc' clusters in results

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak_explorer#103]
I have the following clusters set up in my `riak_explorer.conf` file:

```
clusters.localdev.riak_node = riak@127.0.0.1
clusters.localdev.development_mode = on

clusters.qa1.riak_node = riak@127.0.0.1
clusters.qa1.development_mode = on

clusters.production1.riak_node = riak@127.0.0.1
clusters.production1.development_mode = off
```

But in the 'list clusters' result (`GET /explore/clusters/`), it returns the following:

* qa1
* production1
* localdev
* default

(And also occasionally `adhoc`, though I can't figure out when that happens).

So, two questions:
1. Can we get rid of the 'default' listing, since that's not actually in the config?
2. Is the appearance of the 'adhoc' cluster some sort of user error, or is that still a thing?

**Comment by drewkerrigan** [comment]
The adhoc cluster gets automatically added, and was necessary in a previous implementation of the Riak Mesos Framework. The idea being that if you use control endpoints on a node that doesn't exist in any of the existing clusters, then that cluster is now part of the "adhoc" cluster because it was created at run time instead of at config/start time. I think there is still a place for the "adhoc" cluster, but you're right, it should be intentionally added with an endpoint, or maybe we even support a new "create cluster" endpoint to support it. The problem it was solving doesn't even exist any more in the RMF, so I have no problems with getting rid of at least how it is instantiated now anyway.

And yeah, the fact that the default cluster even shows up when you don't define it is likely an oversight by me, I'll see if I can easily remedy that problem.

**Comment by dmitrizagidulin** [comment]
Tested, works, no longer returns either `default` or `adhoc`. Thanks Drew! Closing.
