### ISSUE TITLE
Do we need the explore /keys/$key endpoint?

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak_explorer#113]
We've got the following endpoints implemented in the Explorer API (listed on our api listing)

```
/explore/nodes/$node/bucket_types/$bucket_type/buckets/$bucket/keys/$key
/explore/nodes/$node/bucket_types/$bucket_type/buckets/$bucket/keys/$key/$resource
```

I don't think we need them, however -- we're fetching the keys via the `/riak` proxy endpoints, not via `/explore`. Does it make sense to clean em up?

**Comment by drewkerrigan** [comment]
:+1:

**Comment by dmitrizagidulin** [comment]
Tested, +1 on removing the two endpoints. 
I ran into behavior I didn't quite expect though. This isn't a huge deal, but for my own curiosity --
with the endpoints removed, a GET to either one of those points now returns an HTTP 200 OK and the following html:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Riak Explorer</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <base href="/" />
<meta name="ember-riak-explorer/config/environment" content="%7B%22modulePrefix%22%3A%22ember-riak-explorer%22%2C%22podModulePrefix%22%3A%22ember-riak-explorer/pods%22%2C%22environment%22%3A%22development%22%2C%22baseURL%22%3A%22/%22%2C%22locationType%22%3A%22auto%22%2C%22EmberENV%22%3A%7B%22FEATURES%22%3A%7B%7D%7D%2C%22APP%22%3A%7B%22name%22%3A%22ember-riak-explorer%22%2C%22version%22%3A%220.0.0+bdf49ba5%22%7D%2C%22contentSecurityPolicy%22%3A%7B%22default-src%22%3A%22%27none%27%22%2C%22script-src%22%3A%22%27self%27%20%27unsafe-inline%27%20%27unsafe-eval%27%22%2C%22connect-src%22%3A%22%27self%27%22%2C%22img-src%22%3A%22%27self%27%22%2C%22style-src%22%3A%22%27self%27%20%27unsafe-inline%27%22%2C%22font-src%22%3A%22%27self%27%22%2C%22media-src%22%3A%22%27self%27%22%7D%2C%22contentSecurityPolicyHeader%22%3A%22Content-Security-Policy-Report-Only%22%2C%22exportApplicationGlobal%22%3Atrue%7D" />
    <link rel="stylesheet" href="assets/ember-riak-explorer.css">

  </head>
  <body>

    <script src="assets/vendor.js"></script>
    <script src="assets/ember-riak-explorer.js"></script>

  </body>
</html>
```

Is that the default behavior for un-implemented routes, for explorer?

**Comment by drewkerrigan** [comment]
Yeah as a matter of fact, that's a good point. I meant to fix this awhile ago. Basically if *any* path isn't explicitly defined as a route in webmachine, it defaults to the static file handler because the backend assumes it must be a file.

Furthermore, the frontend uses "virtual" paths like `http://localhost:9000/cluster/localdev`. That path doesn't exist on the backend, and the only way to make paths like that work is to actually serve index.html. So the logic on the backend ends up being like: "If the file doesn't exist, just serve index.html, otherwise, serve the file from dist/".

I'm not really sure how to solve that problem without explicitly defining all of the "virtual" paths that you guys create on the frontend as basically a symlink to index.html on the backend.

I may be able to to check if the attempted path begins with any of the known backend paths ("/explore", "/riak", "/control", etc) and then if the path doesn't exist, return 404. I'll work on that implementation unless you have any better ideas.

**Comment by dmitrizagidulin** [comment]
That seems like a good solution (checking if the paths begin with /explore, /riak, /control etc). Go for it.

**Comment by drewkerrigan** [comment]
ok, implemented.

**Comment by dmitrizagidulin** [comment]
Brilliant. :) Works now. Thanks!
