### ISSUE TITLE
Riak explorer 1.4.x not working

### ISSUE THREAD

**Issue by es-lab** [basho-labs/riak_explorer#155]
Riak cluster version: 2.1.4

With riak explorer 1.3.0 everything works well, but from the next version (1.4.0, 1.4.1) I get this error in the browser:
<img width="926" alt="screen shot 2017-01-30 at 8 00 56 pm" src="https://cloud.githubusercontent.com/assets/19519449/22434970/e60b4a28-e726-11e6-8973-8018b6479261.png">

**Comment by travisbhartwell** [comment]
It looks like it can't find the `crypto` library. A few questions to help track down what might be gong on:

1. What OS and version are you on? Also, if you could double check you downloaded the matching distribution of Riak Explorer to your platform, because if not, finding the appropriate system crypto libraries will fail.

2. Could you try the following: From the `riak_explorer` directory where you have untarred the distribution, and with Riak Explorer stopped, do this:

First, run the Riak Explorer console, which will bring up an Erlang prompt:
```
$ ./bin/riak_explorer console
```
From the console, first try to load the crypto libraries by typing this:
```
application:ensure_started(crypto).
```

Erlang should respond with `ok`. If it doesn't, please share the output here.

Next, try this:

```
crypto:start().
```

It should either respond with `ok` or `{error,{already_started,crypto}}`. Here it might complain about a missing library. This will give us a clue as to what is missing. If you share the info about your platform, I can help you resolve that.

On my system, here is the output:

```
$ ./bin/riak_explorer console
config is OK
-config /Users/travisbhartwell/tmp/tmp/riak_explorer/data/generated.configs/app.2017.01.31.14.44.31.config -args_file /Users/travisbhartwell/tmp/tmp/riak_explorer/data/generated.configs/vm.2017.01.31.14.44.31.args -vm_args /Users/travisbhartwell/tmp/tmp/riak_explorer/data/generated.configs/vm.2017.01.31.14.44.31.args
Exec:  /Users/travisbhartwell/tmp/tmp/riak_explorer/bin/../erts-5.10.3/bin/erlexec -boot /Users/travisbhartwell/tmp/tmp/riak_explorer/bin/../releases/2.1.0/riak_explorer               -config /Users/travisbhartwell/tmp/tmp/riak_explorer/data/generated.configs/app.2017.01.31.14.44.31.config -args_file /Users/travisbhartwell/tmp/tmp/riak_explorer/data/generated.configs/vm.2017.01.31.14.44.31.args -vm_args /Users/travisbhartwell/tmp/tmp/riak_explorer/data/generated.configs/vm.2017.01.31.14.44.31.args              -pa /Users/travisbhartwell/tmp/tmp/riak_explorer/bin/../lib/basho-patches -- console
Root: /Users/travisbhartwell/tmp/tmp/riak_explorer/bin/..
Erlang R16B02_basho10 (erts-5.10.3) [source] [64-bit] [smp:8:8] [async-threads:64] [hipe] [kernel-poll:true] [frame-pointer]

Eshell V5.10.3  (abort with ^G)
(riak_explorer@127.0.0.1)1> application:ensure_started(crypto).
ok
(riak_explorer@127.0.0.1)2> crypto:start().
{error,{already_started,crypto}}
```

Hope this helps get to the bottom of things.

**Comment by es-lab** [comment]
My os is `macOS Sierra 10.12.2`. I've downloaded this version `riak_explorer-1.4.1-osx-10.11.tar.gz`.

This is the result after running those commands:
```
*******:riak_explorer *******$ bin/riak_explorer console
config is OK
-config /Users/*******/Documents/Resources/orarmd/riak_explorer/data/generated.configs/app.2017.02.02.10.24.42.config -args_file /Users/*******/Documents/Resources/orarmd/riak_explorer/data/generated.configs/vm.2017.02.02.10.24.42.args -vm_args /Users/*******/Documents/Resources/orarmd/riak_explorer/data/generated.configs/vm.2017.02.02.10.24.42.args
!!!!
!!!! WARNING: ulimit -n is 256; 4096 is the recommended minimum.
!!!!
Exec:  /Users/*******/Documents/Resources/orarmd/riak_explorer/bin/../erts-5.10.3/bin/erlexec -boot /Users/*******/Documents/Resources/orarmd/riak_explorer/bin/../releases/2.1.0/riak_explorer               -config /Users/*******/Documents/Resources/orarmd/riak_explorer/data/generated.configs/app.2017.02.02.10.24.42.config -args_file /Users/*******/Documents/Resources/orarmd/riak_explorer/data/generated.configs/vm.2017.02.02.10.24.42.args -vm_args /Users/*******/Documents/Resources/orarmd/riak_explorer/data/generated.configs/vm.2017.02.02.10.24.42.args              -pa /Users/*******/Documents/Resources/orarmd/riak_explorer/bin/../lib/basho-patches -- console
Root: /Users/*******/Documents/Resources/orarmd/riak_explorer/bin/..
Erlang R16B02_basho10 (erts-5.10.3) [source] [64-bit] [smp:8:8] [async-threads:64] [hipe] [kernel-poll:true] [frame-pointer]


=INFO REPORT==== 2-Feb-2017::10:24:42 ===
    alarm_handler: {set,{system_memory_high_watermark,[]}}
Eshell V5.10.3  (abort with ^G)
(riak_explorer@127.0.0.1)1> application:ensure_started(crypto).
ok
(riak_explorer@127.0.0.1)2> crypto:start().
** exception error: undefined function crypto:start/0
(riak_explorer@127.0.0.1)3>
```

**Comment by paultannenbaum** [comment]
@es-lab I have observed dependency problems when upgrading versions in the past. If you are running via a dev build, try removing your `deps` directory and rerunning `make` and `make deps` to properly pull in the correct packages, and then try and rerun explorer.

**Comment by es-lab** [comment]
@paultannenbaum I'm using this version `riak_explorer-1.4.1-osx-10.11.tar.gz` downloaded from `github relases` and there is no deps directory inside it.

**Comment by travisbhartwell** [comment]
@es-lab Sorry I'm just now getting back with you. I don't have 10.12 on my machine at the moment, so I had to get someone else to test for me.

I'm thinking the issue is with how I compiled Erlang on the build system. I have the openssl libraries installed view homebrew, and it links against that. If you don't have that installed, the necessary crypto libraries can't be loaded.

Could you test this, from the terminal in the RIak Explorer directory?
```
otool -L lib/crypto-3.1/priv/lib/crypto.so 
```

It should have output similar to this:
```
lib/crypto-3.1/priv/lib/crypto.so:
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Yours is probably showing something about `libcrypto.1.0.0.dylib` missing.

For now, the solution is to install [HomeBrew](https://brew.sh/) and then install `openssl` with it:

```
brew install openssl
```

Then test Riak Explorer again and let me know if that works. I'll take a closer look and see if requiring users to have Homebrew and Openssl is the best solution long-term.

**Comment by es-lab** [comment]
@travisbhartwell Sorry for the delay, your suggestion worked, now it works perfectly.

P.S.: In this 1.4.1 release should be some "UI updates", but actually I didn't see any updates, it looks the same as 1.3.x.
