### ISSUE TITLE
Add Riak type (EE/OSS) and Riak version to /explore/clusters info

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak_explorer#93]
There is currently no way to easily determine the riak version of a particular cluster or node via an HTTP API. (The only way to get that info is to do [riak version](http://docs.basho.com/riak/latest/ops/running/tools/riak/#version) on the command line).

Nor is there a way to determine whether a user is dealing with an Enterprise Edition or Open-Source riak.

Add these two variables to the result of `/explore/clusters` API. This will enable a lot of intelligence on the GUI side.

Sample result:

```
GET localhost:9000/explore/clusters
{"clusters":[
    {"id":"localdev", "riak_node":"riak@127.0.0.1", 
       "development_mode":false,
       "riak_type": "ee",
       "riak_version": "2.0.6"
    }, ... }
```

**Comment by travisbhartwell** [comment]
@dmitrizagidulin I'm working on this issue.

I've looked at the `riak` command, and it is just a shell script.  Looking at how the `version` command is implemented, it just echos the shell script variable `APP_VERSION` that is found in (in the Riak EE version installed from a .deb, for example) `/usr/lib/riak/lib/env.sh`.  It's not immediately obvious if this is available from the Riak runtime.

The closest I can come up with is the output of `riak-admin status` command, which among other things, outputs the following:

```
riak_kv_version : <<"2.1.0-0-g6e88b24">>
riak_api_version : <<"2.1.1-2-g94a9485">>
```

Would returning the `riak_kv_version` be sufficient for the Riak version for you?

I'm still learning these  codebases, so I might also be missing something.

**Comment by travisbhartwell** [comment]
@dmitrizagidulin I went ahead an implemented this, with the following outputs:

Against Riak OSS version:
```
vagrant@cluster1:~/riak_explorer/rel/riak_explorer/log$ curl http://localhost:9000/explore/clusters
{"clusters":[{"id":"default","riak_node":"riak@127.0.0.1","development_mode":true,"riak_type":"oss","riak_version":"2.1.0-0-g6e88b24"}],"links":{"self":"/explore/clusters"}}
```
Against Riak EE:
```
vagrant@cluster1:~$ curl http://localhost:9000/explore/clusters
{"clusters":[{"id":"default","riak_node":"riak@127.0.0.1","development_mode":true,"riak_type":"oss","riak_version":"2.1.0-0-g6e88b24"}],"links":{"self":"/explore/clusters"}}``
```

Do these looks like what you need?

**Comment by dmitrizagidulin** [comment]
@travisbhartwell So, unfortunately, the riak_kv library version doesn't give us the Riak version (they don't map exactly). (otherwise, I wouldn't make a separate issue to request it be implemented).
Is there any way we can call out to the environment/shell from Erlang, and get the value of that env variable?

**Comment by drewkerrigan** [comment]
@dmitrizagidulin there's currently no precedent (in riak explorer anyway) for making OS executions from the riak node. Doing this would require passing bytecode to the riak node(s) via RPC, and then using those to execute an OS level command, then passing the result back. There's a couple problems with that, including:

* It won't work in all environments; specifically mesos based clusters because the riak/riak-admin commands are useless there because of the containerized nature of the deployment (which was a big reason for even creating riak explorer actually)
* It creates more security concerns than are excusable in exchange for just a version number.

There may be a different way to grab or calculate the version number, but I suggest we table this particular feature for now. Basically what we need is a way to get Riak to tell us the version it's running through existing means (HTTP API), or figure out a way to do it from inside of riak console. Either of those methods would provide us a path to do it from Riak Explorer.

**Comment by dmitrizagidulin** [comment]
@drewkerrigan I see what you mean. (Although I'm surprised there's no other way of determining Riak version from inside Riak/erlang, aside from that environment variable).

@travisbhartwell Yeah, let's punt on the version issue for now. Just the type will be fine. Thanks!

**Comment by dmitrizagidulin** [comment]
Tested, works as expected. 
(The `riak_version` part is being added in PR #105.)
